### ISSUE TITLE
Cluster Beer

### ISSUE THREAD

**Issue by diouck** [ThomasG77/leaflet-browserify#1]
Bonjour,
je voudrai ajouter des cluster dans votre code avec ceci

```
var markerClusters = L.markerClusterGroup();
var bar=   new L.layerJSON({
  url: 'http://overpass-api.de/api/interpreter?data=[out:json];node({lat1},{lon1},{lat2},{lon2})[amenity=bar];out;',
  propertyItems: 'elements',
  propertyTitle: 'tags.name', 
  propertyLoc: ['lat','lon'],
  buildIcon: function(data, title) {
  return attractionIcon;
  },
  buildPopup: function(data, marker) {
    return data.tags.name || null;
  }
});
markerClusters.addLayer( bar);
map.addLayer( markerClusters );
```

Le probleme c'est qu'il n 'affiche plus rien

**Comment by ThomasG77** [comment]
`L.markerClusterGroup()` est dans un plugin Leaflet qui n'est pas dans le code ici (normal, je n'allais pas ajouter du code que je n'utilise pas).

Il vous faudra rajouter le package `leaflet.markercluster`. C'est similaire aux points déjà abordés dans le tuto http://webgeodatavore.com/leaflet-browserify.html

**Comment by diouck** [comment]
Oui je sais mais j'avais deja rajouter dans ton code  les packages de markercluster
 `<script src='https://api.mapbox.com/mapbox.js/plugins/leaflet-markercluster/v0.4.0/leaflet.markercluster.js'></script>
<link href='https://api.mapbox.com/mapbox.js/plugins/leaflet-markercluster/v0.4.0/MarkerCluster.css' rel='stylesheet' />
<link href='https://api.mapbox.com/mapbox.js/plugins/leaflet-markercluster/v0.4.0/MarkerCluster.Default.css' rel='stylesheet' />`

**Comment by ThomasG77** [comment]
Le problème n'est pas lié à mon code du tout. Après quelques tests, je vois que si `bar` n'est pas ajouté à la carte, l'appel à l'Overpass API n'est pas effectué et donc que clusteriser sur rien ne peut pas marcher.

Tu dois faire tes appels en Ajax sans utiliser `L.layerJSON` puis ajouter les markers à ton `markerClusters`.
